{"name": "verifying entering something on search box and clicking search button gives the search results", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Defination.py\", line 34, in I_am_loading_google_url_as\n    d.loadURL(url)\n  File \"C:\\Users\\Ramesh-Shwetha\\PycharmProjects\\True_Fit_Automation_Framework\\utility\\WrapperDriver.py\", line 38, in loadURL\n    self.driver.get(url)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open a browser", "status": "passed", "start": 1540335776127, "stop": 1540335778729}, {"name": "When I am loading google url as \"http://www.google.com\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Defination.py\", line 34, in I_am_loading_google_url_as\n    d.loadURL(url)\n  File \"C:\\Users\\Ramesh-Shwetha\\PycharmProjects\\True_Fit_Automation_Framework\\utility\\WrapperDriver.py\", line 38, in loadURL\n    self.driver.get(url)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1540335778729, "stop": 1540335778907}, {"name": "And I am clicking search button by entering \"True Fit\" on textbox", "status": "skipped", "start": 1540335778910, "stop": 1540335778910}, {"name": "Then I am making sure that I am getting the search results", "status": "skipped", "start": 1540335778910, "stop": 1540335778910}, {"name": "And I am closing the browser", "status": "skipped", "start": 1540335778911, "stop": 1540335778911}], "start": 1540335776122, "stop": 1540335778911, "uuid": "5c63ce93-55d4-4b0a-9c95-4f85d7c4ea12", "historyId": "62ce379cf1e0ec861d5c5a7cb5f5a45e", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Testing True Fit"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}